#!/usr/bin/env python
# PYTHON_ARGCOMPLETE_OK

import argparse, argcomplete

from arm_characterization.data_logger import main as armDataLogger
from arm_characterization.data_analyzer import main as armDataAnalyzer

from drive_characterization.data_logger import main as driveDataLogger
from drive_characterization.data_analyzer import main as driveDataAnalyzer

tool_dict = {
    "logger": {"arm": armDataLogger, "drive": driveDataLogger},
    "analyzer": {"arm": armDataAnalyzer, "drive": driveDataAnalyzer},
}

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="RobotPy characterization tools CLI")
    parser.add_argument("tool_type", choices=list(tool_dict.keys()),
        help="Tool type to use")
    parser.add_argument("mech_type", choices=list(list(tool_dict.values())[0].keys()),
        help="Mechanism type to with that tool")
    argcomplete.autocomplete(parser)
    args = parser.parse_args()

    tool_dict[args.tool_type][args.mech_type]()

