name: CI

on: [push, pull_request]

jobs:
  build:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - uses: actions/setup-python@v2
      with:
        python-version: 3.7
    
    - name: Install Python dependencies
      run: pip install wheel twine black

    - name: Check formatting
      run: black --check --diff ./
     
    - name: Build package
      run: python setup.py bdist_wheel
    
    - name: Upload package to PyPi
      uses: pypa/gh-action-pypi-publish@v1.4.1
      with:
        password: ${{ secrets.PYPI_PASSWORD }}
      if: ${{ github.repository_owner == 'wpilibsuite' && startsWith(github.ref, 'refs/tags/v') }}
